---
- name: "DISPLAY COLLECTIONS"
  hosts: "localhost"
  gather_facts: false

  tasks:
    - name: "DEBUG"
      ansible.builtin.debug:
        msg: "This is the first message"

    # - name: "SLEEP"
    #   ansible.builtin.pause:
    #     seconds: 300

    - name: "LIST COLLECTIONS"
      ansible.builtin.command:
        cmd: "ansible-galaxy collection list --format json"
      register: "collections"

    - name: "PARSE OUTPUT"
      ansible.builtin.set_fact:
        collections_data: "{{ collections.stdout | from_json }}"

    - name: "DISPLAY COLLECTIONS"
      ansible.builtin.debug:
        var: "collections_data"
