---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  system:
    - "jq"

images:
  base_image:
    name: "quay.io/centos/centos:stream9"

additional_build_steps:
  prepend_base:
    - "RUN yum update"

options:
  tags:
    - "ghcr.io/ubajze/ansible-execution-env:latest"
